/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestioncolis;

import classe.connectionbd;
import classe.retrait;
import classe.toutcolis;
import static gestioncolis.formmenu.*;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;




/**
 *
 * @author ILBOUDO Christian
 */
public class formfacture extends javax.swing.JPanel {

    /**
     * Creates new form formretrait
     */
    public formfacture() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnvalider = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtiden = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnimprimer = new javax.swing.JButton();
        jPanelfacture = new javax.swing.JPanel();
        jdate = new javax.swing.JLabel();
        jbienvenu = new javax.swing.JLabel();
        jmenu = new javax.swing.JLabel();
        jexpediteur = new javax.swing.JLabel();
        jrecept = new javax.swing.JLabel();
        jpaquets = new javax.swing.JLabel();
        jtype = new javax.swing.JLabel();
        jtel = new javax.swing.JLabel();
        jville = new javax.swing.JLabel();
        jtire = new javax.swing.JLabel();
        jprixTotal = new javax.swing.JLabel();
        jtiret = new javax.swing.JLabel();
        jtirets = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(230, 231, 232));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 18))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1326, 531));

        btnvalider.setBackground(new java.awt.Color(0, 0, 255));
        btnvalider.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnvalider.setForeground(new java.awt.Color(255, 255, 255));
        btnvalider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Knob-Valid-Green-icon.png"))); // NOI18N
        btnvalider.setText("VALIDER");
        btnvalider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnvalider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvaliderActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel7.setText("Identifiant du colis a récupéré");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel8.setText("Type du colis a récupéré");

        btnimprimer.setBackground(new java.awt.Color(255, 255, 255));
        btnimprimer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnimprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imprimer-icone-8818-48.png"))); // NOI18N
        btnimprimer.setText("IMPRIMER");
        btnimprimer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnimprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimerActionPerformed(evt);
            }
        });

        jPanelfacture.setBackground(new java.awt.Color(255, 255, 255));

        jdate.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jbienvenu.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jmenu.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jexpediteur.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jrecept.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jpaquets.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jtype.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jtel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jville.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jtire.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jprixTotal.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jtiret.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jtirets.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelfactureLayout = new javax.swing.GroupLayout(jPanelfacture);
        jPanelfacture.setLayout(jPanelfactureLayout);
        jPanelfactureLayout.setHorizontalGroup(
            jPanelfactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jtire, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jville, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jtiret, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jtirets, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelfactureLayout.createSequentialGroup()
                .addGroup(jPanelfactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelfactureLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelfactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jexpediteur, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdate, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelfactureLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jrecept, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelfactureLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpaquets, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelfactureLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtype, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelfactureLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelfactureLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jbienvenu, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelfactureLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jprixTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelfactureLayout.setVerticalGroup(
            jPanelfactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelfactureLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jdate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbienvenu, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jexpediteur, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrecept, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpaquets, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtype, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jville, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtire, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtirets, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtiret, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jprixTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtiden, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnvalider, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)))
                .addGap(136, 136, 136)
                .addComponent(jPanelfacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnimprimer)
                .addGap(411, 411, 411))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelfacture, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnimprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtiden, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnvalider, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnimprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimerActionPerformed
        try {
            classe.imprimerfacture.imprimerPanel(jPanelfacture);
        } catch (com.itextpdf.text.DocumentException ex) {
            Logger.getLogger(formfacture.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnimprimerActionPerformed

    private void btnvaliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvaliderActionPerformed
try {
  String identifiant = txtiden.getText().trim();
    String type = txtType.getText().trim();


    // Connexion à la base de données
    c = connectionbd.seconnecter();
    st = c.createStatement();
   
    // Vérification si le colis a été retiré
    String queryRetrait = "SELECT * FROM retrait WHERE identifiant = ?";
    ps = c.prepareStatement(queryRetrait);
    ps.setString(1, identifiant);
    rs = ps.executeQuery();

    if (!rs.next()) {
        // Le colis n'a pas encore été retiré
        JOptionPane.showMessageDialog(null, "Veuillez retirer le colis d'abord.");
    } else {
         // Vérification si le colis a été retiré et récupération des informations du colis
    String queryColis = "SELECT t.*, r.dateretrait FROM toutcolis t INNER JOIN retrait r ON t.identifiant = r.identifiant WHERE t.identifiant = ? AND t.type = ?";
    ps = c.prepareStatement(queryColis);
        ps.setString(1, identifiant);
        ps.setString(2, type);
        rs = ps.executeQuery();

        // Vérification et affichage des informations du colis trouvé
      if (rs.next()) {
            // Récupération des informations nécessaires
            String dateRetrait = rs.getString("dateretrait");
            String expediteur  = rs.getString("expediteur");
            String recepteur = rs.getString("recepteur");
            String nombre_paquets = rs.getString("nbpaquet");
            String typeColis = rs.getString("type");
            String Prixcolis=rs.getString("prix");
            String villeArrivee = rs.getString("arrivee");
            String telRecepteur = rs.getString("telrecepteur");

           

            // Affichage des informations récupérées dans les éléments graphiques correspondants
            
            jdate.setText("La date de retrait est: " + dateRetrait);
            jbienvenu.setText("\t Ticket de caisse\n");
            jmenu.setText("\t ----------------------------------------------------------------\n");
            jexpediteur.setText("Nom complet de l'expediteur: " + expediteur);
            jrecept.setText("Nom complet du recepteur: " + recepteur);
            jpaquets.setText("Nombre de paquet du colis: " + nombre_paquets);
            jtype.setText("Le type de colis: " + typeColis);
            jtel.setText("Numéro de téléphone du recepteur: " + telRecepteur);
            jville.setText("Numéro de téléphone du recepteur: " + villeArrivee);
            jtire.setText("\t ----------------------------------------------------------------\n");
             jtirets.setText("\t ----------------------------------------------------------------\n");
             jtiret.setText("\t ----------------------------------------------------------------\n");
            jprixTotal.setText("Prix Total de la facture: "+Prixcolis+" FCFA ");
            

            // Insérer les informations dans la table retrait
            try {
                String insertQuery = "INSERT INTO facture (identifiant,dateretrait,expediteur, recepteur, nbpaquets, type, telrecep) VALUES (?, ?, ?, ?, ?,?,?)";
                ps = c.prepareStatement(insertQuery);
                ps.setString(1, identifiant);
                ps.setString(2, dateRetrait);
                ps.setString(3, expediteur);
                ps.setString(4, recepteur);
                ps.setString(5, nombre_paquets);
                ps.setString(6, type);
                ps.setString(7, telRecepteur);
                ps.executeUpdate();
                ps.close();
                JOptionPane.showMessageDialog(null, "Enregistré avec succès.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erreur lors de l'insertion dans la table retrait: " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Aucun colis trouvé avec cet identifiant et ce type
            JOptionPane.showMessageDialog(null, "Aucun colis trouvé avec cet identifiant et ce type.");
        }
    }

    // Vider les champs identifiant et type
    
    txtiden.setText("");
    txtType.setText("");
    // Placer le curseur sur le champ identifiant
    txtiden.requestFocus();

    // Fermeture des ressources
    rs.close();
    st.close();
    c.close();

} catch (ClassNotFoundException | SQLException ex) {
    Logger.getLogger(retrait.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null, "Erreur lors de la validation du retrait: " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_btnvaliderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnimprimer;
    private javax.swing.JButton btnvalider;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelfacture;
    private javax.swing.JLabel jbienvenu;
    private javax.swing.JLabel jdate;
    private javax.swing.JLabel jexpediteur;
    private javax.swing.JLabel jmenu;
    private javax.swing.JLabel jpaquets;
    private javax.swing.JLabel jprixTotal;
    private javax.swing.JLabel jrecept;
    private javax.swing.JLabel jtel;
    private javax.swing.JLabel jtire;
    private javax.swing.JLabel jtiret;
    private javax.swing.JLabel jtirets;
    private javax.swing.JLabel jtype;
    private javax.swing.JLabel jville;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtiden;
    // End of variables declaration//GEN-END:variables
}
