/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestioncolis;

import static classe.graphique.Statistiques;
import com.sun.javafx.collections.MappingChange.Map;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;









/**
 *
 * @author ILBOUDO Christian
 */
public class formstatistique extends javax.swing.JPanel {

    /**
     * Creates new form formretrait
     */
    public formstatistique() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnmois = new javax.swing.JButton();
        btnan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnanca = new javax.swing.JButton();
        btnmoisca = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N

        btnmois.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        btnmois.setText("STATISTIQUE MENSUELLE");
        btnmois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoisActionPerformed(evt);
            }
        });

        btnan.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        btnan.setText("STATISTIQUE ANNSUELLE");
        btnan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmois, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnan, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(967, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnmois, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("STATISTIQUE NOMBRE DE COLIS ENVOYES", jPanel1);

        btnanca.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        btnanca.setText("STATISTIQUE ANNSUELLE");
        btnanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnancaActionPerformed(evt);
            }
        });

        btnmoisca.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        btnmoisca.setText("STATISTIQUE MENSUELLE");
        btnmoisca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoiscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmoisca, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnanca, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(967, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnmoisca, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnanca, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("STATISTIQUE CHIFFRE D'AFFAIRE", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnmoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoisActionPerformed
 
DefaultPieDataset datasetColisMois = new DefaultPieDataset();
       
        datasetColisMois.setValue("Janvier", new Integer(10)); // Exemple : 150 colis en 2022
        datasetColisMois.setValue("Fevrier", new Integer(21));
        datasetColisMois.setValue("Juin", new Integer(6));

        JFreeChart chartColisMois = ChartFactory.createPieChart("Nombre de colis envoyés par mois", datasetColisMois, true, true, false);
        ChartFrame frameColisMois = new ChartFrame("Statistiques Mensuelles - Colis", chartColisMois);
        frameColisMois.setVisible(true);
        frameColisMois.setSize(600, 400);
        
       Statistiques();
    }//GEN-LAST:event_btnmoisActionPerformed

    private void btnanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanActionPerformed
        DefaultPieDataset datasetColisMois = new DefaultPieDataset();   
        
        datasetColisMois.setValue("2021", new Integer(10)); // Exemple : 150 colis en 2022
        datasetColisMois.setValue("2024", new Integer(21));
        datasetColisMois.setValue("2023", new Integer(6));
         datasetColisMois.setValue("2023", new Integer(6));

        JFreeChart chartColisMois = ChartFactory.createPieChart("Nombre de colis envoyés par mois", datasetColisMois, true, true, false);
        ChartFrame frameColisMois = new ChartFrame("Statistiques Mensuelles - Colis", chartColisMois);
        frameColisMois.setVisible(true);
        frameColisMois.setSize(600, 400);
    }//GEN-LAST:event_btnanActionPerformed

    private void btnancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnancaActionPerformed
         DefaultPieDataset datasetColisMois = new DefaultPieDataset();   
        
        datasetColisMois.setValue("2021", new Integer(1000)); // Exemple : 150 colis en 2022
        datasetColisMois.setValue("2024", new Integer(2100));
        datasetColisMois.setValue("2023", new Integer(6333));
         datasetColisMois.setValue("2023", new Integer(6230));

        JFreeChart chartColisMois = ChartFactory.createPieChart("Chiffre d'affaire par mois", datasetColisMois, true, true, false);
        ChartFrame frameColisMois = new ChartFrame("Statistiques Mensuelles - Colis", chartColisMois);
        frameColisMois.setVisible(true);
        frameColisMois.setSize(600, 400);
    }//GEN-LAST:event_btnancaActionPerformed

    private void btnmoiscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoiscaActionPerformed
DefaultPieDataset datasetColisMois = new DefaultPieDataset();
       
        datasetColisMois.setValue("Janvier", new Integer(10000)); // Exemple : 150 colis en 2022
        datasetColisMois.setValue("Fevrier", new Integer(28896));
        datasetColisMois.setValue("Juin", new Integer(600001));

        JFreeChart chartColisMois = ChartFactory.createPieChart("Chiffre d'affaire par mois", datasetColisMois, true, true, false);
        ChartFrame frameColisMois = new ChartFrame("Statistiques Mensuelles - Colis", chartColisMois);
        frameColisMois.setVisible(true);
        frameColisMois.setSize(600, 400);     
       
      
    }//GEN-LAST:event_btnmoiscaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnan;
    private javax.swing.JButton btnanca;
    private javax.swing.JButton btnmois;
    private javax.swing.JButton btnmoisca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

   
}
