/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestioncolis;

import classe.connectionbd;
import classe.retrait;
import classe.toutcolis;
import static gestioncolis.formmenu.*;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;




/**
 *
 * @author ILBOUDO Christian
 */
public class formretrait extends javax.swing.JPanel {

    /**
     * Creates new form formretrait
     */
    public formretrait() {
        initComponents();
         dater.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dater = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        btnvalider = new javax.swing.JButton();
        infor = new javax.swing.JPanel();
        jrecepteur = new javax.swing.JLabel();
        jpaquets = new javax.swing.JLabel();
        jtype = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jdate = new javax.swing.JLabel();
        jtel = new javax.swing.JLabel();
        jarrive = new javax.swing.JLabel();
        jexpediteur = new javax.swing.JLabel();
        jrecept = new javax.swing.JLabel();
        information = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtiden = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(230, 231, 232));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RETRAIT DU COLIS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 18))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1326, 531));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel1.setText("DATE");

        btnvalider.setBackground(new java.awt.Color(0, 0, 255));
        btnvalider.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnvalider.setForeground(new java.awt.Color(255, 255, 255));
        btnvalider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Knob-Valid-Green-icon.png"))); // NOI18N
        btnvalider.setText("VALIDER");
        btnvalider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnvalider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvaliderActionPerformed(evt);
            }
        });

        infor.setBackground(new java.awt.Color(230, 231, 232));
        infor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMATION DU COLIS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tw Cen MT", 1, 18))); // NOI18N

        jrecepteur.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jpaquets.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jtype.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jdate.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jtel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jarrive.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jexpediteur.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jrecept.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        information.setBackground(new java.awt.Color(230, 231, 232));
        information.setText("                                      DETAIL ");
        information.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout inforLayout = new javax.swing.GroupLayout(infor);
        infor.setLayout(inforLayout);
        inforLayout.setHorizontalGroup(
            inforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inforLayout.createSequentialGroup()
                .addGroup(inforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inforLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(inforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jpaquets, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                            .addComponent(jtype, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(inforLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jexpediteur, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inforLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jdate, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(138, 138, 138)
                .addGroup(inforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrecepteur, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(inforLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel12)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(inforLayout.createSequentialGroup()
                .addGroup(inforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inforLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(inforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtel, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jarrive, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrecept, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(inforLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(information, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inforLayout.setVerticalGroup(
            inforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inforLayout.createSequentialGroup()
                .addComponent(information, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(inforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(inforLayout.createSequentialGroup()
                        .addComponent(jrecepteur, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(inforLayout.createSequentialGroup()
                        .addComponent(jdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jexpediteur, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrecept, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jpaquets, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtype, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jarrive, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel7.setText("Identifiant du colis a récupéré");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel8.setText("Type du colis a récupéré");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtiden, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(175, 175, 175))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dater, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(314, 314, 314)
                                .addComponent(btnvalider, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(infor, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(652, 652, 652))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dater, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtiden, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnvalider, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(infor, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1326, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnvaliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvaliderActionPerformed
try {
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
    // Récupération et formatage des données entrées par l'utilisateur
    String dateretrait = dateFormat.format(dater.getDate());
    String identifiant = txtiden.getText().trim();
    String type = txtType.getText().trim();

    // Connexion à la base de données
    c = connectionbd.seconnecter();
    st = c.createStatement();
    
    // Vérification si le colis a déjà été retiré
    String Query = "SELECT * FROM retrait WHERE identifiant = '" + identifiant + "'";
    rs = st.executeQuery(Query);

    if (rs.next()) {
        // Le colis a déjà été retiré
        JOptionPane.showMessageDialog(null, "Ce colis a déjà été retiré.");}
    else {
        // Exécution de la requête SQL pour récupérer les informations du colis correspondant
        String query = "SELECT * FROM toutcolis WHERE identifiant = '" + identifiant + "' AND type = '" + type + "'";
        rs = st.executeQuery(query);

        // Vérification et affichage des informations du colis trouvé
        if (rs.next()) {
            // Récupération des informations nécessaires
            String expediteur = rs.getString("expediteur");
            String recepteur = rs.getString("recepteur");
            String nombre_paquets = rs.getString("nbpaquet");
            String typeColis = rs.getString("type");
            String villeArrivee = rs.getString("arrivee");
            String telRecepteur = rs.getString("telrecepteur");

            // Affichage des informations récupérées dans les éléments graphiques correspondants
            jdate.setText("La date de retrait est: " + dateretrait);
            jexpediteur.setText("Nom complet de l'expediteur: " + expediteur);
            jrecept.setText("Nom complet du recepteur: " + recepteur);
            jpaquets.setText("Nombre de paquet du colis: " + nombre_paquets);
            jtype.setText("Le type de colis: " + typeColis);
            jarrive.setText("La ville d'arrivée: " + villeArrivee);
            jtel.setText("Numéro de téléphone du recepteur: " + telRecepteur);

            // Insérer les informations dans la table retrait
            try {
                String insertQuery = "INSERT INTO retrait (identifiant, dateretrait, expediteur, recepteur, nbpaquet, type, arrivee, telrecepteur) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                ps = c.prepareStatement(insertQuery);
                ps.setString(1, identifiant);
                ps.setString(2, dateretrait);
                ps.setString(3, expediteur);
                ps.setString(4, recepteur);
                ps.setString(5, nombre_paquets);
                ps.setString(6, typeColis);
                ps.setString(7, villeArrivee);
                ps.setString(8, telRecepteur);
                ps.executeUpdate();
                ps.close();
                JOptionPane.showMessageDialog(null, "Information enregistré avec succès.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erreur lors de l'insertion dans la table retrait: " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Aucun colis trouvé avec cet identifiant et ce type
            JOptionPane.showMessageDialog(null, "Aucun colis trouvé avec cet identifiant et ce type.");
        }
    }

    // Vider les champs identifiant et type
    dater.setDate(new Date());
    txtiden.setText("");
    txtType.setText("");
    // Placer le curseur sur le champ identifiant
    txtiden.requestFocus();

    // Fermeture des ressources
    rs.close();
    st.close();
    c.close();

} catch (ClassNotFoundException | SQLException ex) {
    Logger.getLogger(retrait.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null, "Erreur lors de la validation du retrait: " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
}


    }//GEN-LAST:event_btnvaliderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnvalider;
    private com.toedter.calendar.JDateChooser dater;
    private javax.swing.JPanel infor;
    private javax.swing.JTextField information;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jarrive;
    private javax.swing.JLabel jdate;
    private javax.swing.JLabel jexpediteur;
    private javax.swing.JLabel jpaquets;
    private javax.swing.JLabel jrecept;
    private javax.swing.JLabel jrecepteur;
    private javax.swing.JLabel jtel;
    private javax.swing.JLabel jtype;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtiden;
    // End of variables declaration//GEN-END:variables
}
